version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm resgistry for updates every week
    schedule:
      interval: "weekly"
    target-branch: "main"