# Sample Cloud Build configuration for Auth service
# Copy this to your project root and customize as needed

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '-t'
      - '$_IMAGE_NAME:latest'
      - '-f'
      - './apps/$_SERVICE_NAME/Dockerfile'
      - '--target'
      - 'production'
      - '.'
    
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_IMAGE_NAME:latest'

  # Deploy to GKE (optional - you can handle this separately)
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/$_SERVICE_NAME-deployment.yaml'
      - '--image=$_IMAGE_NAME:$COMMIT_SHA'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'

substitutions:
  _SERVICE_NAME: 'auth'
  _IMAGE_NAME: 'gcr.io/$movie-app-464210/movie-app-auth'
  _GKE_CLUSTER: 'movie-app-cluster'
  _GKE_LOCATION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
