apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: maximilienbey/movie-app_reservation:v0.0.7
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /reservations/health
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /reservations/health
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
          env:
            - name: JWT_SECRET
              value: "mysecret"
            - name: DATABASE_URL
              value: "postgresql://movie:movie@movie-app-postgresql:5432/movie?schema=public"
            - name : RABBIT_MQ_URL
              value: "amqp://movie:movie@movie-app-rabbitmq:5672"