apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: maximilienbey/movie-app_movie:v0.0.2
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              value: "mysecret"
            - name: DATABASE_URL
              value: "postgresql://movie:movie@movie-app-postgresql:5432/movie?schema=public"
            - name : RABBIT_MQ_URL
              value: "amqp://movie:movie@movie-app-rabbitmq:5672"