apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: "movie-app-movie:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env: 
          - name: MOVIE_PORT
            value: "3000"
          - name: RABBIT_MQ_USER_QUEUE
            value: "user"
          - name: RABBIT_MQ_AUTH_QUEUE
            value: "auth"
          - name: DATABASE_URL
            value: postgresql://movie:movie@movie-app-postgresql:5432/movie?schema=public
          - name : RABBIT_MQ_URL
            value: amqp://movie:movie@movie-app-rabbitmq:5672