apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: "movie-app-auth:latest"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
        env: 
          - name: AUTH_PORT
            value: "3001"
          - name: JWT_SECRET
            value: "secret"
          - name: RABBIT_MQ_USER_QUEUE
            value: "user"
          - name: RABBIT_MQ_AUTH_QUEUE
            value: "auth"
          - name: DATABASE_URL
            value: postgresql://movie:movie@movie-app-postgresql:5432/movie?schema=public
          - name : RABBIT_MQ_URL
            value: amqp://movie:movie@movie-app-rabbitmq:5672