apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-service
  labels:
    app: cinema-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinema-service
  template:
    metadata:
      labels:
        app: cinema-service
    spec:
      serviceAccountName: movie-app-service-account
      containers:
      - name: cinema-service
        image: us-central1-docker.pkg.dev/movie-app-464210/movie-app-repo/cinema:latest
        ports:
        - containerPort: 3004
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-config
              key: url
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-config
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-config
              key: port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-config
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-config
              key: password
        - name: RMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-config
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cinema-service
  labels:
    app: cinema-service
spec:
  selector:
    app: cinema-service
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
  type: ClusterIP
