# Updated secrets with actual values from Terraform
apiVersion: v1
kind: Secret
metadata:
  name: database-config
  namespace: default
type: Opaque
stringData:
  url: "postgresql://movie:$(DB_PASSWORD)@10.91.0.3:5432/movie"
  host: "10.91.0.3"
  port: "5432"
  database: "movie"
  username: "movie"
  # Password will be injected from Secret Manager

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"
  DATABASE_HOST: "10.91.0.3"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "movie"
  DATABASE_USER: "movie"
