# Kubernetes configuration for database secrets
apiVersion: v1
kind: Secret
metadata:
  name: database-config
type: Opaque
stringData:
  url: "postgresql://movie:PASSWORD@PRIVATE_IP:5432/movie"
  host: "PRIVATE_IP"
  port: "5432"
  database: "movie"
  username: "movie"
  password: "PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-config
type: Opaque
stringData:
  host: "REDIS_HOST"
  port: "6379"

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  PORT: "3000"
