name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions: 
      contents: read
      pull-requests: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2
      - name: Use node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint:ci
      - name: Test
        run: pnpm run test
      - name: Check for version change in package.json
        id: version_check
        run: |
          git fetch --depth=2
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            VERSION_OLD=$(git show HEAD^:./package.json | jq -r .version)
          else
            echo "First commit or no previous version to compare."
            VERSION_OLD=""
          fi
          
          VERSION_NEW=$(jq -r .version package.json)
          
          if [[ "$VERSION_OLD" != "$VERSION_NEW" ]]; then
            echo "New version detected: $VERSION_NEW"
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
            echo "version=$VERSION_NEW" >> $GITHUB_ENV
            echo "::set-output name=version_changed::true"
            echo "::set-output name=version::$VERSION_NEW"
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
            echo "::set-output name=version_changed::false"
          fi
        shell: bash
    outputs:
      version_changed: ${{ steps.version_check.outputs.version_changed }}
      version: ${{ steps.version_check.outputs.version }}

  call_release_workflow:
    needs: build
    permissions: write-all
    if: ${{ needs.build.outputs.version_changed == 'true' }}
    uses: ./.github/workflows/release.yml
    with: 
      version: ${{ needs.build.outputs.version }}