name: Delivery

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
    secrets:
      TOKEN:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - auth
          - cinema
          - movie
          - reservation
          - user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
          fetch-depth: 2 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          echo "Building and releasing ${{ matrix.module }} container"
          docker build --platform=linux/amd64 . -f apps/${{ matrix.module }}/Dockerfile --no-cache -t maximilienbey/movie-app_${{ matrix.module }}:v${{ inputs.version }}
          docker push maximilienbey/movie-app_${{ matrix.module }}:v${{ inputs.version }}
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: |
            Publish the draft of the release v${{ inputs.version }} to update Kubernetes Engine
          draft: true
          prerelease: false