name: Release Workflow

on:
  release:
    types: [published]

jobs:
  on-release-published:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Deploy on Google Cloud using Helm
        run: echo "[TODO] Deploying version ${{ steps.get_version.outputs.VERSION }} on Google Cloud using Helm"