name: Deployment

on:
  release:
    types: [ published ]

jobs:
  on-release-published:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v4
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Install Google Cloud plugins
        run: |
          gcloud components install gke-gcloud-auth-plugin
      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials movie-app --zone europe-west2-b --project ${{ secrets.GCP_PROJECT_ID }}
      - name: Replace version in Helm templates
        run: |
          find helm/movie-app/templates -type f -exec sed -i 's/0.0.1/${{ steps.get_version.outputs.VERSION }}/g' {} \;
      - name: Helm upgrade
        run: |
          helm upgrade --install movie-app helm/movie-app