name: Create Release

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        includes:
          - image: auth
          - module: cinema
          - module: movie
          - module: reservation
          - module: user
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.TOKEN }}
          fetch-depth: 2 
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          echo "Building and releasing ${{ matrix.module }} container"
          docker build --platform=linux/amd64 . -f apps/${{ matrix.module }}/Dockerfile --no-cache -t maximilienbey/movie-app_${{ matrix.module }}:v${{ inputs.version }}
          docker push maximilienbey/movie-app_${{ matrix.module }}:v${{ inputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: |
            This is a release for version ${{ inputs.version }}, which is automatically created by the release workflow.
            Release it to deploy the new version to the production environment.
          draft: true
          prerelease: false