name: Create Release

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: |
            This is a release for version ${{ inputs.version }}, which is automatically created by the release workflow.
            Release it to deploy the new version to the production environment.
          draft: true
          prerelease: false